image: python:3.10

stages:
  - test
  - lint
  - types
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - poetry run python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

Unit Tests:
  stage: test
  script:
    - poetry run pytest

Python Code Lint:
  stage: lint
  script:
    - poetry run black .

Static Type check:
  stage: types
  script:
    - poetry run mypy .
