image: python:3.10

stages:
  - test
  - lint
  - types
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .venv/
    - ${HOME}/.cache/pypoetry/

before_script:
  - if [ ! -d ".venv" ]; then pip install poetry; fi
  - poetry config virtualenvs.create true
  - poetry config virtualenvs.in-project true
  - if [ ! -d ".venv" ]; then poetry install; fi
  - if [ ! -f ".venv/bin/torch" ]; then poetry run python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu; fi
Unit Tests:
  stage: test
  script:
    - poetry run pytest

Python Code Lint:
  stage: lint
  script:
    - poetry run black .

Static Type check:
  stage: types
  script:
    - poetry run mypy .
